# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.2.9-12-gdae2f70
_src_path: https://github.com/algorandfoundation/algokit-beaker-default-template.git
algod_port: 4001
algod_server: http://localhost
algod_token: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
author_email: ''
author_name: ''
deployment_language: typescript
ide_vscode: true
indexer_port: 8980
indexer_server: http://localhost
indexer_token: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
project_name: cicd-ts
python_linter: ruff
use_github_actions: true
use_python_black: true
use_python_mypy: true
use_python_pip_audit: true
use_python_pytest: true

